SYSTEM_NAME="86box"
SYSTEM_FULLNAME="86Box"
SYSTEM_MANUFACTURER="PC"
SYSTEM_RELEASE="1981"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/86box"
SYSTEM_EXTENSION=".cfg .86box"
SYSTEM_PLATFORM="pc"
SYSTEM_THEME="86box"
