SYSTEM_NAME="aram"
SYSTEM_FULLNAME="ARAM - Korean Feature Phone"
SYSTEM_MANUFACTURER="Korean Mobile"
SYSTEM_RELEASE="2000"
SYSTEM_HARDWARE="portable"
SYSTEM_PATH="/storage/roms/aram"
SYSTEM_EXTENSION=".dat .jar .zip .ZIP"
SYSTEM_PLATFORM="j2me"
SYSTEM_THEME="j2me"
SYSTEM_WIKI_PATH="j2me"
