# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)

PKG_NAME="armsx2-sa"
PKG_VERSION="917bc678654480f351279eaa2dfee2d8008a2b76"
PKG_ARCH="aarch64"
PKG_LICENSE="GPL-3.0-or-later"
PKG_SITE="https://github.com/ARMSX2/ARMSX2"
PKG_URL="${PKG_SITE}.git"
PKG_GIT_CLONE_BRANCH="master"
GET_HANDLER_SUPPORT="git"
PKG_LONGDESC="ARMSX2 is a fork of PCSX2 with native ARM64 recompilers."
PKG_TOOLCHAIN="manual"
PKG_BUILD_FLAGS="speed"

PKG_DEPENDS_TARGET="toolchain llvm:host SDL3 libpng zlib libjpeg-turbo zstd lz4 libwebp freetype \
                    plutosvg curl libpcap ffmpeg libX11 libXext qt6 ecm shaderc rapidyaml \
                    kddockwidgets alsa-lib dbus ${VULKAN}"

if [ "${DISPLAYSERVER}" = "wl" ]; then
  PKG_DEPENDS_TARGET+=" wayland ${WINDOWMANAGER} xwayland xrandr libXi"
fi

if [ "${OPENGL_SUPPORT}" = "yes" ]; then
  PKG_DEPENDS_TARGET+=" ${OPENGL} libglvnd"
elif [ "${OPENGLES_SUPPORT}" = "yes" ]; then
  PKG_DEPENDS_TARGET+=" ${OPENGLES}"
fi

ARMSX2_CMAKE_OPTS=(
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
  -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON
  -DENABLE_TESTS=OFF
  -DENABLE_QT_UI=ON
  -DENABLE_GSRUNNER=OFF
  -DENABLE_SETCAP=OFF
  -DUSE_BACKTRACE=OFF
  -DUSE_VULKAN=ON
  -DUSE_OPENGL=ON
  -DDISABLE_ADVANCE_SIMD=ON
  -DWAYLAND_API=ON
  -DX11_API=ON
  -DOVERRIDE_HOST_PAGE_SIZE=0x1000
  -DOVERRIDE_HOST_CACHE_LINE_SIZE=64
)

# RK3576 contains Cortex-A72/A53 cores. Keep generated code at ARMv8.0 so the
# binary does not acquire ARMv8.1 LSE instructions from the upstream default.
case ${DEVICE} in
  RK3576)
    ARMSX2_CMAKE_OPTS+=(
      -DCMAKE_C_FLAGS=-march=armv8-a+crc+crypto
      -DCMAKE_CXX_FLAGS=-march=armv8-a+crc+crypto
    )
  ;;
esac

PATCHES_URL="https://github.com/PCSX2/pcsx2_patches/releases/download/latest/patches.zip"

make_target() {
  for _v in CFLAGS CXXFLAGS LDFLAGS; do
    export ${_v}="$(echo ${!_v} | sed 's/-mabi=lp64//g; s/-mtune=[^ ]*//g')"
  done

  # LLVM bitcode generated by IPO must be linked with lld. Remove a global
  # ROCKNIX linker selection before CMake appends it after *_FLAGS_INIT.
  export LDFLAGS="$(echo ${LDFLAGS} | sed 's/-fuse-ld=[^ ]*//g')"

  # Some third-party configure steps invoke clang without inheriting
  # CMAKE_*_COMPILER_TARGET, so keep the target triple in the environment too.
  export CFLAGS="--target=${TARGET_NAME} ${CFLAGS}"
  export CXXFLAGS="--target=${TARGET_NAME} ${CXXFLAGS}"
  export LDFLAGS="--target=${TARGET_NAME} ${LDFLAGS}"

  mkdir -p "${PKG_BUILD}/.${TARGET_NAME}"
  cd "${PKG_BUILD}/.${TARGET_NAME}"

  local -a tgt_opts=(
    -G Ninja
    -S "${PKG_BUILD}"
    -B "${PKG_BUILD}/.${TARGET_NAME}"
    -DCMAKE_INSTALL_PREFIX=/usr
    -DCMAKE_MAKE_PROGRAM=ninja
    -DCMAKE_C_COMPILER="${TOOLCHAIN}/bin/clang"
    -DCMAKE_CXX_COMPILER="${TOOLCHAIN}/bin/clang++"
    -DCMAKE_AR="${TOOLCHAIN}/bin/llvm-ar"
    -DCMAKE_RANLIB="${TOOLCHAIN}/bin/llvm-ranlib"
    -DCMAKE_NM="${TOOLCHAIN}/bin/llvm-nm"
    -DCMAKE_OBJCOPY="${TOOLCHAIN}/bin/llvm-objcopy"
    -DCMAKE_OBJDUMP="${TOOLCHAIN}/bin/llvm-objdump"
    -DCMAKE_STRIP="${TOOLCHAIN}/bin/llvm-strip"
    -DCMAKE_C_COMPILER_AR="${TOOLCHAIN}/bin/llvm-ar"
    -DCMAKE_CXX_COMPILER_AR="${TOOLCHAIN}/bin/llvm-ar"
    -DCMAKE_C_COMPILER_RANLIB="${TOOLCHAIN}/bin/llvm-ranlib"
    -DCMAKE_CXX_COMPILER_RANLIB="${TOOLCHAIN}/bin/llvm-ranlib"
    -DCMAKE_EXE_LINKER_FLAGS_INIT="-fuse-ld=lld"
    -DCMAKE_MODULE_LINKER_FLAGS_INIT="-fuse-ld=lld"
    -DCMAKE_SHARED_LINKER_FLAGS_INIT="-fuse-ld=lld"
    -DCMAKE_SYSTEM_NAME=Linux
    -DCMAKE_SYSTEM_PROCESSOR=${TARGET_ARCH}
    -DCMAKE_C_COMPILER_TARGET=${TARGET_NAME}
    -DCMAKE_CXX_COMPILER_TARGET=${TARGET_NAME}
    -DCMAKE_SYSROOT="${SYSROOT_PREFIX}"
    -DCMAKE_FIND_ROOT_PATH="${SYSROOT_PREFIX}"
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
    "${ARMSX2_CMAKE_OPTS[@]}"
  )

  cmake "${tgt_opts[@]}"
  cmake --build "${PKG_BUILD}/.${TARGET_NAME}"
  wget -c -t 5 -O "${PKG_BUILD}/.${TARGET_NAME}/bin/resources/patches.zip" "${PATCHES_URL}"
}

makeinstall_target() {
  mkdir -p ${INSTALL}/usr/bin
  cp -rf ${PKG_DIR}/scripts/* ${INSTALL}/usr/bin
  chmod 755 ${INSTALL}/usr/bin/*

  mkdir -p ${INSTALL}/usr/share/armsx2-sa
  cp -rf ${PKG_BUILD}/.${TARGET_NAME}/bin/* ${INSTALL}/usr/share/armsx2-sa

  mkdir -p ${INSTALL}/usr/config
  cp -rf ${PKG_DIR}/config/ARMSX2 ${INSTALL}/usr/config
}

post_install() {
  case ${DEVICE} in
    SM*)
      GRAPHICS="export MESA_LOADER_DRIVER_OVERRIDE=zink"
    ;;
    *)
      GRAPHICS=""
    ;;
  esac

  sed -e "s/@GRAPHICS@/${GRAPHICS}/g" \
      -i ${INSTALL}/usr/bin/start_armsx2.sh
}
