#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)

. /etc/profile
set_kill set "-9 xenia_edge"

CONF_DIR="/storage/.config/xenia"
CONTENT_DIR="${CONF_DIR}/content"
CACHE_DIR="${CONF_DIR}/cache"
DEFAULT_CONF_FILE="/usr/config/xenia/xenia-edge.config.toml"
CONF_FILE="${CONF_DIR}/xenia-edge.config.toml"
ROM="$1"
PLATFORM="$2"
GAME="${ROM##*/}"

VSYNC=$(get_setting vsync "${PLATFORM}" "${GAME}")
VSYNC="${VSYNC:-true}"
DEBUG_LOGGING=$(get_setting debug_logging "${PLATFORM}" "${GAME}")
DEBUG_LOGGING="${DEBUG_LOGGING:-false}"

# Current Xenia maps its VSync UI toggle to the inverse of Vulkan immediate
# present mode: VSync on disables tearing/VRR-capable immediate presentation.
case "${VSYNC}" in
  true|1|on|yes)
    VULKAN_ALLOW_PRESENT_MODE_IMMEDIATE="false"
    ;;
  *)
    VULKAN_ALLOW_PRESENT_MODE_IMMEDIATE="true"
    ;;
esac

mkdir -p "${CONF_DIR}" "${CONTENT_DIR}" "${CACHE_DIR}"

# Install the packaged defaults only for a new profile. Preserve all existing
# user changes and files generated by earlier Xenia runs.
if [ ! -f "${CONF_FILE}" ]; then
  if [ -f "${CONF_DIR}/xenia-canary.config.toml" ]; then
    cp "${CONF_DIR}/xenia-canary.config.toml" "${CONF_FILE}"
  elif [ -f "${DEFAULT_CONF_FILE}" ]; then
    cp "${DEFAULT_CONF_FILE}" "${CONF_FILE}"
  fi
  if [ -d "/usr/config/xenia/content" ]; then
    cp -rn /usr/config/xenia/content/* "${CONTENT_DIR}/" 2>/dev/null || true
  fi
fi

# Xenia's Linux frontend currently uses GTK/X11 and an XCB Vulkan surface.
export DISPLAY="${DISPLAY:-:0}"
export GDK_BACKEND="x11"
export SDL_VIDEODRIVER="x11"
# Use the installed gdk-pixbuf loader cache. An inherited /dev/null module
# file prevents GTK from loading PNG icons.
unset GDK_PIXBUF_MODULE_FILE

# GTK creates an XWayland window, so match the process PID rather than a
# Wayland app_id that isn't present.
sway_fullscreen "xenia_edge" "pidof" &

ARGS=(
  "--gpu=vulkan"
  "--vulkan_allow_present_mode_immediate=${VULKAN_ALLOW_PRESENT_MODE_IMMEDIATE}"
  "--apu=alsa"
  "--hid=sdl"
  "--break_on_debugbreak=false"
  "--fullscreen=true"
  "--storage_root=${CONF_DIR}"
  "--content_root=${CONTENT_DIR}"
  "--cache_root=${CACHE_DIR}"
)

case "${DEBUG_LOGGING}" in
  true|1|on|yes)
    ARGS+=(
      "--flush_log=true"
      "--log_file=${CONF_DIR}/xenia.log"
      "--log_level=2"
      "--log_to_stdout=true"
    )
    ;;
  *)
    ARGS+=(
      "--flush_log=false"
      "--log_file=/dev/null"
      "--log_level=0"
      "--log_to_stdout=false"
    )
    ;;
esac

if [ -n "${ROM}" ]; then
  ARGS+=("${ROM}")
fi

/usr/bin/xenia_edge "${ARGS[@]}"
