#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)

. /etc/profile
set_kill set "-9 xenia_edge"

CONF_DIR="/storage/.config/xenia"
CONTENT_DIR="${CONF_DIR}/content"
CACHE_DIR="${CONF_DIR}/cache"
DEFAULT_CONF_FILE="/usr/config/xenia/xenia-edge.config.toml"
CONF_FILE="${CONF_DIR}/xenia-edge.config.toml"
ROM="$1"
PLATFORM="$2"
GAME="${ROM##*/}"

VSYNC=$(get_setting vsync "${PLATFORM}" "${GAME}")
VSYNC="${VSYNC:-true}"

mkdir -p "${CONF_DIR}" "${CONTENT_DIR}" "${CACHE_DIR}"

# Install the packaged defaults only for a new profile. Preserve all existing
# user changes and files generated by earlier Xenia runs.
if [ ! -f "${CONF_FILE}" ]; then
  if [ -f "${CONF_DIR}/xenia-canary.config.toml" ]; then
    cp "${CONF_DIR}/xenia-canary.config.toml" "${CONF_FILE}"
  elif [ -f "${DEFAULT_CONF_FILE}" ]; then
    cp "${DEFAULT_CONF_FILE}" "${CONF_FILE}"
  fi
fi

# Xenia's Linux frontend currently uses GTK/X11 and an XCB Vulkan surface.
export DISPLAY="${DISPLAY:-:0}"
export GDK_BACKEND="x11"
export SDL_VIDEODRIVER="x11"

# GTK creates an XWayland window, so match the process PID rather than a
# Wayland app_id that isn't present.
sway_fullscreen "xenia_edge" "pidof" &

ARGS=(
  "--gpu=vulkan"
  "--apu=alsa"
  "--hid=sdl"
  "--break_on_debugbreak=false"
  "--fullscreen=true"
  "--storage_root=${CONF_DIR}"
  "--content_root=${CONTENT_DIR}"
  "--cache_root=${CACHE_DIR}"
  "--vsync=${VSYNC}"
)

if [ -n "${ROM}" ]; then
  ARGS+=("${ROM}")
fi

/usr/bin/xenia_edge "${ARGS[@]}"

